name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: chmod +x ci/build-app.sh
